Adding GH Actions workflow for version checking
hugheylab/drat pull request #1
Opened 2022-03-04 15:19 UTC by JSchoenbachler

This adds a GH Actions workflow that does the following:
1. Uses R to read lab package versions on CRAN and within the drat repo.
2. Calculates which drat packages meet a version difference threshold (>5 patch releases, >2 minor releases, or 1 major release).
3. Closes any open GH Issues labeled `cran-update`
4. Creates an issue for each package exceeding one of the version difference thresholds with the label of `cran-update`.

2022-03-05 12:43 UTC, jakejh requested changes

2022-03-05 12:43 UTC, jakejh commented on .github/workflows/cran-check.yaml
> +                        tstrsplit(drat_version, '.', fixed = TRUE, type.convert = TRUE)]
This line should start only two spaces past the previous, similar to lines 34 and 35.

2022-03-05 12:43 UTC, jakejh commented on .github/workflows/cran-check.yaml
> +                    tstrsplit(cran_version, '.', fixed = TRUE, type.convert = TRUE)]
This line should start only two spaces past the previous, similar to lines 34 and 35.

2022-03-05 12:43 UTC, jakejh commented on .github/workflows/cran-check.yaml
> +          needsUpdatesOutput = paste0(packages$name, '---', packages$drat_version, '---', packages$cran_version, collapse = '", "')
Please add line breaks as so:

```r
needsUpdatesOutput = paste0(
  packages$name, '---', packages$drat_version,
  '---', packages$cran_version, collapse = '", "')
```

2022-03-05 12:43 UTC, jakejh commented on .github/workflows/cran-check.yaml
> +          s = sprintf('echo \'::set-output name=value::%s\'', needsUpdatesOutput)
Can we change this to below for readability?

```r
s = sprintf("echo '::set-output name=value::%s'", needsUpdatesOutput)
```

2022-03-05 12:43 UTC, jakejh commented on .github/workflows/cran-check.yaml
> +        value: ${{fromJson(needs.check_version_number.outputs.matrix)}}
For consistency, add whitespace around double braces.

2022-03-05 12:43 UTC, jakejh commented on .github/workflows/cran-check.yaml
> +          query: 'label:cran-update is:open'
For consistency, probably use double quotes.

2022-03-05 12:43 UTC, jakejh commented on .github/workflows/cran-check.yaml
> +# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
Are these first two lines really still applicable?

2022-03-07 18:44 UTC, JSchoenbachler commented
@jakejh Changes have been made per your requests.

2022-03-08 17:15 UTC, jakejh approved these changes

2022-03-08 17:22 UTC, JSchoenbachler commented
@jakejh I actually don't have write access to this repository, could you merge?

2022-03-08 17:41 UTC, merged